# Generated by Django 4.2.23 on 2025-07-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("excerpt", models.CharField(blank=True, max_length=200, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="img")),
                ("date", models.DateField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("content", models.TextField()),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, null=True, to="page_content.tag"
                    ),
                ),
            ],
        ),
    ]
