# Generated by Django 4.2.23 on 2025-07-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page_content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecontent",
            name="content_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="content_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="content_gl",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="excerpt_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="excerpt_es",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="excerpt_gl",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="title_en",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="title_es",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="title_gl",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
