# Generated by Django 4.2.23 on 2025-07-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page_content", "0002_pagecontent_content_en_pagecontent_content_es_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagecontent",
            options={
                "ordering": ["-date", "title"],
                "verbose_name": "Page Content",
                "verbose_name_plural": "Page Contents",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Tag", "verbose_name_plural": "Tags"},
        ),
        migrations.RemoveField(
            model_name="pagecontent",
            name="image",
        ),
        migrations.AlterField(
            model_name="pagecontent",
            name="content",
            field=models.TextField(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="pagecontent",
            name="content_en",
            field=models.TextField(null=True, verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="pagecontent",
            name="content_es",
            field=models.TextField(null=True, verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="pagecontent",
            name="content_gl",
            field=models.TextField(null=True, verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="pagecontent",
            name="date",
            field=models.DateField(auto_now=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="pagecontent",
            name="excerpt",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Excerpt"
            ),
        ),
        migrations.AlterField(
            model_name="pagecontent",
            name="excerpt_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Excerpt"
            ),
        ),
        migrations.AlterField(
            model_name="pagecontent",
            name="excerpt_es",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Excerpt"
            ),
        ),
        migrations.AlterField(
            model_name="pagecontent",
            name="excerpt_gl",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Excerpt"
            ),
        ),
        migrations.AlterField(
            model_name="pagecontent",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="pagecontent",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="page_content.tag", verbose_name="Tags"
            ),
        ),
        migrations.AlterField(
            model_name="pagecontent",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="pagecontent",
            name="title_en",
            field=models.CharField(max_length=150, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="pagecontent",
            name="title_es",
            field=models.CharField(max_length=150, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="pagecontent",
            name="title_gl",
            field=models.CharField(max_length=150, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=20, unique=True, verbose_name="Name"),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        upload_to="gallery_images/", verbose_name="Image File"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Caption"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="images",
                        to="page_content.tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                related_name="page_contents",
                to="page_content.image",
                verbose_name="Associated Images",
            ),
        ),
    ]
