# Generated by Django 4.2.23 on 2025-07-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("page_content", "0003_alter_pagecontent_options_alter_tag_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagecontent",
            name="images",
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="featured_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="featured_on_page",
                to="page_content.image",
                verbose_name="Featured Image",
            ),
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="gallery_images",
            field=models.ManyToManyField(
                blank=True,
                related_name="pages_in_gallery",
                to="page_content.image",
                verbose_name="Gallery Images",
            ),
        ),
    ]
