# Generated by Django 4.2.23 on 2025-07-28 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "page_content",
            "0004_remove_pagecontent_images_pagecontent_featured_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagecontent",
            name="featured_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="featured_on_page",
                to="page_content.image",
                verbose_name="Featured Image",
            ),
        ),
    ]
