# Generated by Django 4.2.23 on 2025-08-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page_content", "0005_alter_pagecontent_featured_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagecontent",
            options={
                "ordering": ["sort_order", "-date", "title"],
                "verbose_name": "Page Content",
                "verbose_name_plural": "Page Contents",
            },
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
