# Generated by Django 4.2.23 on 2025-08-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("page_content", "0006_alter_pagecontent_options_pagecontent_sort_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagecontent",
            options={
                "ordering": ["-sort_order", "-date", "title"],
                "verbose_name": "Page Content",
                "verbose_name_plural": "Page Contents",
            },
        ),
    ]
