# Generated by Django 4.2.23 on 2025-08-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page_content", "0007_alter_pagecontent_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="tags",
        ),
        migrations.AddField(
            model_name="image",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="image",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
