# Generated by Django 5.2.4 on 2025-08-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page_content", "0008_remove_image_tags_image_hidden_image_sort_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="Hidden in Gallery"),
        ),
    ]
