# Generated by Django 4.2.23 on 2025-07-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_first_name",
                    models.CharField(max_length=100, verbose_name="Guest First Name"),
                ),
                (
                    "guest_last_name",
                    models.CharField(max_length=100, verbose_name="Guest Last Name"),
                ),
                (
                    "guest_email",
                    models.EmailField(max_length=254, verbose_name="Guest Email"),
                ),
                (
                    "guest_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Guest Phone"
                    ),
                ),
                ("check_in_date", models.DateField(verbose_name="Check-in Date")),
                ("check_out_date", models.DateField(verbose_name="Check-out Date")),
                (
                    "num_adults",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Number of Adults"
                    ),
                ),
                (
                    "num_children",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Number of Children"
                    ),
                ),
                (
                    "total_guests",
                    models.PositiveIntegerField(
                        verbose_name="Total Guests (Calculated)"
                    ),
                ),
                (
                    "daily_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Daily Rate at Booking",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total Price"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "payment_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Payment Transaction ID",
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Deposit Amount",
                    ),
                ),
                (
                    "is_email_verified",
                    models.BooleanField(default=False, verbose_name="Email Verified"),
                ),
                (
                    "special_requests",
                    models.TextField(blank=True, verbose_name="Special Requests"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("checked_out", "Checked Out"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reservation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Reservation Date"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
            ],
            options={
                "verbose_name": "House Reservation",
                "verbose_name_plural": "House Reservations",
                "ordering": ["check_in_date", "check_out_date"],
            },
        ),
    ]
