# Generated by Django 4.2.23 on 2025-07-28 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Guest First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Guest Last Name"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Guest Email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Guest Phone"
                    ),
                ),
                (
                    "vat",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Guest vat"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reservation",
            name="main_guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guest_reservation",
                to="reservation.guest",
                verbose_name="Guest",
            ),
        ),
    ]
