# Generated by Django 4.2.23 on 2025-07-28 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_guest_reservation_main_guest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guest",
            options={
                "ordering": ["last_name", "name"],
                "verbose_name": "Guest",
                "verbose_name_plural": "Guests",
            },
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="guest_email",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="guest_first_name",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="guest_last_name",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="guest_phone",
        ),
        migrations.AddField(
            model_name="reservation",
            name="other_guests",
            field=models.ManyToManyField(
                blank=True,
                related_name="other_reservations",
                to="reservation.guest",
                verbose_name="Other Guests",
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Guest Email"
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="vat",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Guest VAT/Tax ID"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="main_guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_reservations",
                to="reservation.guest",
                verbose_name="Main Guest",
            ),
        ),
    ]
