# Generated by Django 4.2.23 on 2025-07-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservation",
            "0003_alter_guest_options_remove_reservation_guest_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="adult",
            field=models.BooleanField(default=False, verbose_name="Guest adult"),
            preserve_default=False,
        ),
    ]
