# Generated by Django 4.2.23 on 2025-07-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0004_guest_adult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Guest Email"),
        ),
    ]
