# Generated by Django 4.2.23 on 2025-07-31 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0005_alter_guest_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Guest Email"
            ),
        ),
    ]
