# Generated by Django 5.2.4 on 2025-08-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0006_alter_guest_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
            ],
        ),
    ]
