# Generated by Django 5.2.4 on 2025-08-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0007_dailyprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days_number", models.PositiveIntegerField()),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("percentage", models.BooleanField(default=True)),
            ],
        ),
    ]
