# Generated by Django 5.2.4 on 2025-09-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0008_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="address",
            field=models.CharField(
                default="", max_length=100, verbose_name="Guest Address"
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="address_state",
            field=models.CharField(
                default="", max_length=100, verbose_name="Guest State"
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="country",
            field=models.CharField(
                default="", max_length=100, verbose_name="Guest Country"
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("NIF", "NIF"),
                    ("DNI", "DNI"),
                    ("NIE", "NIE"),
                    ("PASSPORT", "Passport"),
                    ("DRIVING_LICENSE", "Driving License"),
                ],
                default="NIF",
                max_length=100,
                verbose_name="Document Type",
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="last_name2",
            field=models.CharField(
                default="", max_length=100, verbose_name="Guest Last Name"
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="mobile",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Guest Phone"
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="nacionality",
            field=models.CharField(
                default="", max_length=100, verbose_name="Nacionality"
            ),
        ),
    ]
