# Generated by Django 5.2.4 on 2025-09-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservation",
            "0009_guest_address_guest_address_state_guest_country_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guest",
            options={
                "ordering": ["name", "vat"],
                "verbose_name": "Inquilino",
                "verbose_name_plural": "Inquilino",
            },
        ),
        migrations.AddField(
            model_name="guest",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha nacimiento"
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("male", "Hombre"), ("female", "Mujer")],
                max_length=100,
                null=True,
                verbose_name="Sexo",
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="address",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Dirección"
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="address_state",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Provincia/Estado"
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="adult",
            field=models.BooleanField(blank=True, null=True, verbose_name="Adulto"),
        ),
        migrations.AlterField(
            model_name="guest",
            name="country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Pais"
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("NIF", "NIF"),
                    ("DNI", "DNI"),
                    ("NIE", "NIE"),
                    ("PASSPORT", "Passport"),
                    ("DRIVING_LICENSE", "Driving License"),
                ],
                default="NIF",
                max_length=100,
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Primer apellido"
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="last_name2",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Segundo apellido"
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="mobile",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Móbil"
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="nacionality",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nacionalidad"
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="guest",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Teléfono"
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="vat",
            field=models.CharField(max_length=20, verbose_name="Nº de documento"),
        ),
    ]
