# Generated by Django 5.2.4 on 2025-10-08 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0010_alter_guest_options_guest_birth_date_guest_sex_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="daily_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Daily Rate at Booking",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="main_guest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_reservations",
                to="reservation.guest",
                verbose_name="Main Guest",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="num_adults",
            field=models.PositiveIntegerField(
                blank=True, default=1, verbose_name="Number of Adults"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="num_children",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Number of Children"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="total_guests",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Total Guests (Calculated)"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="total_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total Price",
            ),
        ),
    ]
