# Generated by Django 5.2.4 on 2025-10-09 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0011_alter_reservation_daily_rate_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guest",
            options={
                "ordering": ["name", "vat"],
                "verbose_name": "Huesped",
                "verbose_name_plural": "Huespedes",
            },
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["check_in_date", "check_out_date"],
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
            },
        ),
        migrations.AlterField(
            model_name="reservation",
            name="check_in_date",
            field=models.DateField(verbose_name="Fecha Check-in"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="check_out_date",
            field=models.DateField(verbose_name="Fecha Check-out"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="deposit_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Deposito",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última actualización"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="main_guest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_reservations",
                to="reservation.guest",
                verbose_name="Huesped principal",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="num_adults",
            field=models.PositiveIntegerField(
                blank=True, default=1, verbose_name="Numero de Adultos"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="num_children",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Numero de Niños"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="other_guests",
            field=models.ManyToManyField(
                blank=True,
                related_name="other_reservations",
                to="reservation.guest",
                verbose_name="Otros Huespedes",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("paid", "Pagado"),
                    ("refunded", "Devuelto"),
                    ("failed", "Fallo"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Estado del pago",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Fecha Reserva"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("confirmed", "Confirmado"),
                    ("checked_in", "Check In"),
                    ("checked_out", "Check Out"),
                    ("cancelled", "Cancelado"),
                    ("no_show", "No Show"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="total_guests",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Nº Total (Calculado)"
            ),
        ),
    ]
