# Generated by Django 5.2.4 on 2025-10-12 18:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0012_alter_guest_options_alter_reservation_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationEditToken",
            fields=[
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used", models.BooleanField(default=False)),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservation.reservation",
                    ),
                ),
            ],
        ),
    ]
