# Generated by Django 5.2.4 on 2025-10-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0013_reservationedittoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="vat",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Nº de documento"
            ),
        ),
    ]
