# Generated by Django 5.2.4 on 2025-10-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0014_alter_guest_vat"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="documment_support",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Soporte del documento",
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="relationship",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Parentesco"
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="zip",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Código postal"
            ),
        ),
    ]
