# Generated by Django 5.2.9 on 2026-01-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0015_guest_documment_support_guest_relationship_guest_zip"),
    ]

    operations = [
        migrations.CreateModel(
            name="DateRangeMinDays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                ("min_days", models.PositiveIntegerField(verbose_name="Minimum Days")),
            ],
        ),
        migrations.AlterField(
            model_name="guest",
            name="relationship",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
