# Generated by Django 5.2.4 on 2025-09-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "excerpt",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Asunto"
                    ),
                ),
                (
                    "excerpt_es",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Asunto"
                    ),
                ),
                (
                    "excerpt_en",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Asunto"
                    ),
                ),
                (
                    "excerpt_gl",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Asunto"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="Contenido"),
                ),
                (
                    "content_es",
                    models.TextField(blank=True, null=True, verbose_name="Contenido"),
                ),
                (
                    "content_en",
                    models.TextField(blank=True, null=True, verbose_name="Contenido"),
                ),
                (
                    "content_gl",
                    models.TextField(blank=True, null=True, verbose_name="Contenido"),
                ),
            ],
            options={
                "verbose_name": "Plantilla Correo",
                "verbose_name_plural": "Plantillas Correos",
            },
        ),
    ]
