# Generated by Django 5.2.4 on 2025-10-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Nombre Plantilla"
            ),
        ),
    ]
