# Generated by Django 4.2.23 on 2025-08-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Name")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("phone", models.CharField(max_length=9, verbose_name="Phone")),
                ("address", models.CharField(max_length=200, verbose_name="Address")),
                (
                    "address_link",
                    models.CharField(max_length=200, verbose_name="Address Link"),
                ),
            ],
        ),
    ]
