# Generated by Django 5.2.4 on 2025-09-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basedata",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="gallery_images/",
                verbose_name="Image File",
            ),
        ),
    ]
