# Generated by Django 5.2.4 on 2025-09-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_data", "0002_basedata_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="basedata",
            name="email_app_password",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Contraseña aplicacion email"
            ),
        ),
        migrations.AddField(
            model_name="basedata",
            name="phone2",
            field=models.CharField(blank=True, max_length=9, verbose_name="Phone2"),
        ),
        migrations.AddField(
            model_name="basedata",
            name="phone3",
            field=models.CharField(blank=True, max_length=9, verbose_name="Phone3"),
        ),
    ]
