# Generated by Django 5.2.4 on 2025-09-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_data", "0003_basedata_email_app_password_basedata_phone2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basedata",
            name="phone",
            field=models.CharField(max_length=15, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="basedata",
            name="phone2",
            field=models.CharField(blank=True, max_length=15, verbose_name="Phone2"),
        ),
        migrations.AlterField(
            model_name="basedata",
            name="phone3",
            field=models.CharField(blank=True, max_length=15, verbose_name="Phone3"),
        ),
    ]
