# Generated by Django 5.2.4 on 2025-10-09 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_data", "0004_alter_basedata_phone_alter_basedata_phone2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basedata",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="basedata",
            name="phone2",
        ),
        migrations.RemoveField(
            model_name="basedata",
            name="phone3",
        ),
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=15, verbose_name="Phone Number"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Description (e.g., Main, Office, Mobile)",
                    ),
                ),
                (
                    "base_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="base_data.basedata",
                        verbose_name="Base Data",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teléfono",
                "verbose_name_plural": "Teléfonos",
            },
        ),
    ]
