# Generated by Django 5.2.9 on 2026-01-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_data", "0005_remove_basedata_phone_remove_basedata_phone2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonenumber",
            name="min_nights",
            field=models.PositiveIntegerField(default=3),
        ),
    ]
