// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'
	| 'gl'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * A​c​c​e​p​t
	 */
	accept: string
	/**
	 * A​d​d​r​e​s​s
	 */
	address: string
	/**
	 * A​r​r​i​v​a​l​ ​d​a​t​e
	 */
	arrival_date: string
	/**
	 * B​o​o​k
	 */
	book: string
	/**
	 * C​h​e​c​k​ ​A​v​a​i​l​a​b​i​l​i​t​y
	 */
	check_availability: string
	/**
	 * C​o​n​t​a​c​t
	 */
	contact: string
	/**
	 * C​o​o​k​i​e​s​ ​P​o​l​i​c​y
	 */
	cookies_policy: string
	/**
	 * D​e​p​a​r​t​u​r​e​ ​d​a​t​e
	 */
	departure_date: string
	/**
	 * G​a​l​l​e​r​y
	 */
	gallery: string
	/**
	 * H​o​m​e
	 */
	home: string
	/**
	 * L​a​n​g​u​a​g​e
	 */
	language: string
	/**
	 * L​e​g​a​l​ ​N​o​t​i​c​e
	 */
	legal_notice: string
	/**
	 * L​o​c​a​t​i​o​n
	 */
	location: string
	/**
	 * L​o​c​a​t​i​o​n​s
	 */
	locations: string
	/**
	 * E​m​a​i​l
	 */
	mail: string
	/**
	 * M​e​s​s​a​g​e
	 */
	message: string
	/**
	 * M​o​r​e​ ​p​h​o​t​o​s
	 */
	more_photos: string
	/**
	 * N​a​m​e
	 */
	name: string
	/**
	 * N​º​ ​g​u​e​s​t
	 */
	n_guest: string
	/**
	 * P​h​o​n​e
	 */
	phone: string
	/**
	 * p​r​i​v​a​c​y​ ​p​o​l​i​t​i​c
	 */
	privacy_politic: string
	/**
	 * R​a​t​e​s
	 */
	rates: string
	/**
	 * Reservation Request
	 */
	reservation_request: string
	/**
	 * R​o​o​m​s
	 */
	rooms: string
	/**
	 * S​e​n​d​ ​M​e​s​s​a​g​e
	 */
	send_message: string
	/**
	 * W​h​a​t​ ​t​o​ ​v​i​s​i​t
	 */
	what_to_visit: string
	/**
	 * W​r​i​t​e​ ​y​o​u​r​ ​m​e​s​s​a​g​e
	 */
	write_your_message: string
	/**
	 * Y​o​u​r​ ​e​m​a​i​l
	 */
	your_email: string
	/**
	 * Y​o​u​r​ ​n​a​m​e
	 */
	your_name: string
	/**
	 * T​h​i​s​ ​l​o​g​ ​w​a​s​ ​c​a​l​l​e​d​ ​f​r​o​m​ ​'​{​f​i​l​e​N​a​m​e​}​'
	 * @param {string} fileName
	 */
	log: RequiredParams<'fileName'>
	/**
	 * e​n
	 */
	locale: string
}

export type TranslationFunctions = {
	/**
	 * Accept
	 */
	accept: () => LocalizedString
	/**
	 * Address
	 */
	address: () => LocalizedString
	/**
	 * Arrival date
	 */
	arrival_date: () => LocalizedString
	/**
	 * Book
	 */
	book: () => LocalizedString
	/**
	 * Check Availability
	 */
	check_availability: () => LocalizedString
	/**
	 * Contact
	 */
	contact: () => LocalizedString
	/**
	 * Cookies Policy
	 */
	cookies_policy: () => LocalizedString
	/**
	 * Departure date
	 */
	departure_date: () => LocalizedString
	/**
	 * Gallery
	 */
	gallery: () => LocalizedString
	/**
	 * Home
	 */
	home: () => LocalizedString
	/**
	 * Language
	 */
	language: () => LocalizedString
	/**
	 * Legal Notice
	 */
	legal_notice: () => LocalizedString
	/**
	 * Location
	 */
	location: () => LocalizedString
	/**
	 * Locations
	 */
	locations: () => LocalizedString
	/**
	 * Email
	 */
	mail: () => LocalizedString
	/**
	 * Message
	 */
	message: () => LocalizedString
	/**
	 * More photos
	 */
	more_photos: () => LocalizedString
	/**
	 * Name
	 */
	name: () => LocalizedString
	/**
	 * Nº guest
	 */
	n_guest: () => LocalizedString
	/**
	 * Phone
	 */
	phone: () => LocalizedString
	/**
	 * privacy politic
	 */
	privacy_politic: () => LocalizedString
	/**
	 * Rates
	 */
	rates: () => LocalizedString
	/**
	 * Reservation Request
	 */
	reservation_request: () => LocalizedString
	/**
	 * Rooms
	 */
	rooms: () => LocalizedString
	/**
	 * Send Message
	 */
	send_message: () => LocalizedString
	/**
	 * What to visit
	 */
	what_to_visit: () => LocalizedString
	/**
	 * Write your message
	 */
	write_your_message: () => LocalizedString
	/**
	 * Your email
	 */
	your_email: () => LocalizedString
	/**
	 * Your name
	 */
	your_name: () => LocalizedString
	/**
	 * This log was called from '{fileName}'
	 */
	log: (arg: { fileName: string }) => LocalizedString
	/**
	 * en
	 */
	locale: () => LocalizedString
}

export type Formatters = {}
